package com.allan.model;

import java.util.HashSet;
import java.util.Set;

import com.allan.domain.USER_ROLE;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
public class User {

    // User Entity must have a primary key
    // PK auto generated by spring
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // whenever we fetch user detail from the front end,
    // password will not come(keep pw secret not exposed in frontend)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    private String email;

    private String fullName;

    private String mobile;

    private USER_ROLE role = USER_ROLE.ROLE_CUSTOMER;

    private boolean emailVerified = false;

    private LocalDateTime createdAt;

    // we save a customer address at first purchase so that we have their addresses
    // always

    // User to address relation => one to many
    @OneToMany
    private Set<Address> addresses = new HashSet<>();

    // keep track of used coupons so the customer uses the coupon only once

    // many user can access same coupons and one user can use many coupons
    @ManyToMany
    @JsonIgnore
    private Set<Coupon> usedCoupons = new HashSet<>();

}
