package com.allan.mapper;

import com.allan.model.Coupon;
import com.allan.model.CouponRedemption;
import com.allan.model.Promotion;
import com.allan.model.PromotionAudit;
import com.allan.model.PromotionReward;
import com.allan.model.PromotionRule;
import com.allan.request.PromotionRewardRequest;
import com.allan.request.PromotionRuleRequest;
import com.allan.response.CouponResponse;
import com.allan.response.CouponUsageResponse;
import com.allan.response.PromotionAuditResponse;
import com.allan.response.PromotionResponse;
import com.allan.response.PromotionRewardResponse;
import com.allan.response.PromotionRuleResponse;
import org.springframework.stereotype.Component;

import java.util.Collections;
import java.util.List;

/**
 * Maps {@link Promotion}, {@link Coupon}, and related entities to their
 * outbound response shapes and converts inbound request records to entities.
 *
 * <p><strong>Security contract — two strict rules:</strong>
 * <ol>
 *   <li>Entities are NEVER serialized directly to JSON. Every API response
 *       passes through this mapper. This ensures internal fields
 *       ({@code @Version}, lazy collections, seller IDs on rewards) are
 *       never accidentally exposed to the wrong audience.</li>
 *   <li>Requests are NEVER bound directly to entities. {@link #toEntity(PromotionRuleRequest)}
 *       and {@link #toEntity(PromotionRewardRequest)} exist so controllers
 *       never use {@code @RequestBody PromotionRule}/{@code PromotionReward}
 *       directly — doing so would let a client set {@code id} and, via the
 *       JPA association, potentially the parent {@code Promotion} itself.
 *       These methods copy only the fields a client is allowed to supply;
 *       the {@code Promotion} association is always attached by the service
 *       layer, never by the client.</li>
 * </ol>
 *
 * <p><strong>Lazy loading contract:</strong> never call any method on this
 * mapper with an entity whose collections ({@code rules}, {@code rewards},
 * {@code coupons}) are uninitialized lazy proxies. All callers must either:
 * <ul>
 *   <li>Map inside a {@code @Transactional(readOnly = true)} service method, or</li>
 *   <li>Use a repository query with {@code JOIN FETCH} on the required associations
 *       (e.g. {@code PromotionRepository.findByIdWithRulesAndRewards()}).</li>
 * </ul>
 * Violating this contract throws {@code LazyInitializationException} at runtime
 * with {@code spring.jpa.open-in-view=false}, which is required in this project.
 *
 * <p><strong>Null safety:</strong> all collection mappings use
 * {@link Collections#emptyList()} as the null guard — never return null
 * for a list field. The frontend can always iterate safely.
 *
 * <p><strong>UGX monetary fields:</strong> all {@code long} monetary values
 * (minimumOrderValue, maximumDiscountAmount, reward value for FLAT_OFF) are
 * passed through unchanged in whole UGX shillings. No conversion, no rounding,
 * no floating-point. {@link #formatRewardValue(PromotionReward)} produces the
 * pre-formatted UGX display string with thousand separators.
 *
 * <p><strong>Customer-facing responses:</strong> this mapper intentionally has
 * NO method that maps a full {@code Promotion} or {@code Coupon} to a
 * customer-visible response. The customer checkout validation response
 * ({@code ValidateCouponResponse}) is built directly from evaluation results
 * in {@code CheckoutCouponController} — so there is no code path that could
 * accidentally serialize internal fields (rule thresholds, seller IDs,
 * usage counts) into a customer-visible payload.
 */
@Component
public class PromotionMapper {

    // ═════════════════════════════════════════════════════════════════════════
    // REQUEST → ENTITY   (inbound: client-supplied data → JPA entity)
    // ═════════════════════════════════════════════════════════════════════════

    /**
     * Converts a {@link PromotionRuleRequest} record to a {@link PromotionRule}
     * entity ready for persistence.
     *
     * <p>Only fields the client is permitted to supply are copied.
     * {@code id} is never set — always generated by the DB.
     * {@code promotion} is never set here — the service layer attaches it
     * after this method returns.
     *
     * @param request validated inbound rule request, must not be null
     * @return a detached {@link PromotionRule} with no {@code id} or
     *         {@code promotion} association set
     */
    public PromotionRule toEntity(PromotionRuleRequest request) {
        PromotionRule rule = new PromotionRule();
        rule.setRuleType(request.ruleType());
        rule.setOperator(request.operator());
        rule.setValue(request.value().trim().toUpperCase()); // normalize on ingestion
        rule.setDescription(request.description());
        return rule;
    }

    /**
     * Converts a {@link PromotionRewardRequest} record to a
     * {@link PromotionReward} entity ready for persistence.
     *
     * <p>Same contract as {@link #toEntity(PromotionRuleRequest)} —
     * {@code id} and {@code promotion} are never set here.
     *
     * @param request validated inbound reward request, must not be null
     * @return a detached {@link PromotionReward} with no {@code id} or
     *         {@code promotion} association set
     */
    public PromotionReward toEntity(PromotionRewardRequest request) {
        PromotionReward reward = new PromotionReward();
        reward.setRewardType(request.rewardType());
        reward.setValue(request.value());
        reward.setLabel(request.label());
        reward.setApplicableSellerId(request.applicableSellerId());
        return reward;
    }

    // ═════════════════════════════════════════════════════════════════════════
    // ENTITY → RESPONSE  (outbound: JPA entity → API response)
    // ═════════════════════════════════════════════════════════════════════════

    // ── Promotion ─────────────────────────────────────────────────────────────

    /**
     * Maps a {@link Promotion} to a {@link PromotionResponse}.
     *
     * <p>Requires {@code promotion.getRules()} and
     * {@code promotion.getRewards()} to be initialized. Use
     * {@code PromotionRepository.findByIdWithRulesAndRewards()} before calling.
     *
     * <p>The {@code editable} flag on nested rules and rewards is derived
     * from {@code hasRedemptions} — pass the result of
     * {@code CouponRedemptionRepository.existsByPromotionIdAndReversedFalse(id)}
     * as {@code false} when the promotion has active redemptions.
     *
     * @param promotion      fully loaded promotion entity
     * @param hasRedemptions true if any confirmed redemption exists for this
     *                       promotion — marks rules and rewards as non-editable
     */
    public PromotionResponse toResponse(Promotion promotion, boolean hasRedemptions) {
        boolean editable = !hasRedemptions;

        List<PromotionRuleResponse> rules = promotion.getRules() != null
                ? promotion.getRules().stream()
                        .map(rule -> toRuleResponse(rule, editable))
                        .toList()
                : Collections.emptyList();

        List<PromotionRewardResponse> rewards = promotion.getRewards() != null
                ? promotion.getRewards().stream()
                        .map(reward -> toRewardResponse(reward, editable))
                        .toList()
                : Collections.emptyList();

        int totalCoupons = promotion.getCoupons() != null
                ? promotion.getCoupons().size()
                : 0;

        return new PromotionResponse(
                promotion.getId(),
                promotion.getSellerId(),
                promotion.getName(),
                promotion.getDescription(),
                promotion.getType().name(),
                promotion.getScope().name(),
                promotion.getStatus().name(),
                promotion.getPriority(),
                promotion.isStackable(),
                promotion.isExclusive(),
                promotion.getMinimumOrderValue(),       // UGX long — no conversion
                promotion.getMaximumDiscountAmount(),   // UGX long — no conversion
                promotion.getStartsAt(),
                promotion.getEndsAt(),
                promotion.isLive(),                     // entity domain helper
                promotion.isCodeBased(),                // entity domain helper
                totalCoupons,
                rules,
                rewards,
                promotion.getCreatedAt(),
                promotion.getUpdatedAt(),
                promotion.getCreatedBy()
        );
    }

    /**
     * Convenience overload for contexts where the caller has already
     * determined there are no redemptions (e.g. freshly created DRAFT
     * promotions). Defaults {@code hasRedemptions = false}.
     */
    public PromotionResponse toResponse(Promotion promotion) {
        return toResponse(promotion, false);
    }

    /**
     * Maps a list of {@link Promotion} entities to a list of
     * {@link PromotionResponse} objects.
     *
     * <p>All promotions in the list are marked {@code editable = true}
     * (hasRedemptions = false). Use the two-argument overload for lists
     * where per-promotion redemption state matters.
     */
    public List<PromotionResponse> toPromotionResponseList(List<Promotion> promotions) {
        if (promotions == null || promotions.isEmpty()) return Collections.emptyList();
        return promotions.stream()
                .map(this::toResponse)
                .toList();
    }

    // ── Rule ──────────────────────────────────────────────────────────────────

    /**
     * Maps a {@link PromotionRule} entity to a {@link PromotionRuleResponse}.
     *
     * @param rule     the rule entity, must not be null
     * @param editable pass the result of {@code !hasRedemptions} from the
     *                 service layer — drives the edit/delete UI controls
     */
    public PromotionRuleResponse toRuleResponse(PromotionRule rule, boolean editable) {
        return new PromotionRuleResponse(
                rule.getId(),
                rule.getPromotion().getId(),
                rule.getRuleType().name(),
                rule.getOperator().name(),
                rule.getValue(),
                rule.getDescription(),
                editable
        );
    }

    /**
     * Single-arg overload used when editable state is not yet known.
     * Defaults to {@code editable = false} (safe default — never show
     * edit controls when editability is uncertain).
     */
    public PromotionRuleResponse toRuleResponse(PromotionRule rule) {
        return toRuleResponse(rule, false);
    }

    public List<PromotionRuleResponse> toRuleResponseList(
            List<PromotionRule> rules, boolean editable) {
        if (rules == null || rules.isEmpty()) return Collections.emptyList();
        return rules.stream()
                .map(rule -> toRuleResponse(rule, editable))
                .toList();
    }

    // ── Reward ────────────────────────────────────────────────────────────────

    /**
     * Maps a {@link PromotionReward} entity to a {@link PromotionRewardResponse}.
     * Computes {@link PromotionRewardResponse#formattedValue()} so the
     * frontend never switches on {@code rewardType} for display logic.
     *
     * @param reward   the reward entity, must not be null
     * @param editable same contract as {@link #toRuleResponse(PromotionRule, boolean)}
     */
    public PromotionRewardResponse toRewardResponse(PromotionReward reward, boolean editable) {
        return new PromotionRewardResponse(
                reward.getId(),
                reward.getPromotion().getId(),
                reward.getRewardType().name(),
                reward.getValue(),
                formatRewardValue(reward),      // pre-formatted UGX display string
                reward.getLabel(),
                reward.getApplicableSellerId(),
                editable
        );
    }

    /**
     * Single-arg overload — defaults to {@code editable = false}.
     */
    public PromotionRewardResponse toRewardResponse(PromotionReward reward) {
        return toRewardResponse(reward, false);
    }

    public List<PromotionRewardResponse> toRewardResponseList(
            List<PromotionReward> rewards, boolean editable) {
        if (rewards == null || rewards.isEmpty()) return Collections.emptyList();
        return rewards.stream()
                .map(reward -> toRewardResponse(reward, editable))
                .toList();
    }

    // ── Coupon ────────────────────────────────────────────────────────────────

    /**
     * Maps a {@link Coupon} to a {@link CouponResponse}.
     * Includes computed fields: {@code remainingUses} and {@code available}
     * derived from entity domain helpers — no extra DB call needed.
     */
    public CouponResponse toResponse(Coupon coupon) {
        return new CouponResponse(
                coupon.getId(),
                coupon.getPromotion().getId(),
                coupon.getPromotion().getName(),
                coupon.getCode(),
                coupon.getStatus().name(),
                coupon.getUsageLimit(),
                coupon.getUsedCount(),
                coupon.getUsagePerCustomer(),
                coupon.remainingUses(),     // entity domain helper — no DB call
                coupon.isAvailable(),       // entity domain helper — no DB call
                coupon.getCreatedAt(),
                coupon.getUpdatedAt()
        );
    }

    public List<CouponResponse> toCouponResponseList(List<Coupon> coupons) {
        if (coupons == null || coupons.isEmpty()) return Collections.emptyList();
        return coupons.stream()
                .map(this::toResponse)
                .toList();
    }

    // ── Coupon usage / analytics ──────────────────────────────────────────────

    /**
     * Builds a {@link CouponUsageResponse} from a coupon entity and
     * pre-computed aggregate values fetched by the service layer.
     *
     * <p>Aggregate values (totalDiscountGrantedUgx, reversalCount, etc.)
     * come from {@code CouponRedemptionRepository} queries — they are NOT
     * derived from the coupon entity itself to avoid loading the full
     * redemptions collection.
     *
     * @param coupon                 the coupon entity (requires promotion loaded)
     * @param totalDiscountGrantedUgx sum of discount on non-reversed redemptions
     * @param reversalCount          count of reversed redemptions
     * @param totalRefundedUgx       sum of discount on reversed redemptions
     * @param redemptionSummaries    paginated list of individual redemptions
     */
    public CouponUsageResponse toUsageResponse(
            Coupon coupon,
            long totalDiscountGrantedUgx,
            int reversalCount,
            long totalRefundedUgx,
            List<CouponUsageResponse.RedemptionSummary> redemptionSummaries) {

        return new CouponUsageResponse(
                coupon.getId(),
                coupon.getCode(),
                coupon.getUsedCount(),
                coupon.getUsageLimit(),
                coupon.remainingUses(),
                totalDiscountGrantedUgx,
                reversalCount,
                totalRefundedUgx,
                redemptionSummaries != null
                        ? redemptionSummaries
                        : Collections.emptyList()
        );
    }

    /**
     * Maps a {@link CouponRedemption} entity to a
     * {@link CouponUsageResponse.RedemptionSummary}.
     * Computes {@code effectiveDiscountRate} as a ratio — double is
     * appropriate here because it is a derived ratio, not a monetary value.
     */
    public CouponUsageResponse.RedemptionSummary toRedemptionSummary(
            CouponRedemption redemption) {

        double rate = redemption.getCartTotalAtRedemption() > 0
                ? (double) redemption.getDiscount()
                        / redemption.getCartTotalAtRedemption()
                : 0.0;

        return new CouponUsageResponse.RedemptionSummary(
                redemption.getId(),
                redemption.getUserId(),
                redemption.getOrderId(),
                redemption.getDiscount(),
                redemption.getCartTotalAtRedemption(),
                rate,
                redemption.isReversed(),
                redemption.getRedeemedAt(),
                redemption.getReversedAt()
        );
    }

    // ── Audit log ─────────────────────────────────────────────────────────────

    /**
     * Maps a {@link PromotionAudit} entry to a {@link PromotionAuditResponse}.
     * The audit log is append-only — this is always a read-only mapping.
     */
    public PromotionAuditResponse toAuditResponse(PromotionAudit audit) {
        return new PromotionAuditResponse(
                audit.getId(),
                audit.getPromotion().getId(),
                audit.getAction(),
                audit.getOldValue(),
                audit.getNewValue(),
                audit.getActor(),
                audit.getNotes(),
                audit.getCreatedAt()
        );
    }

    public List<PromotionAuditResponse> toAuditResponseList(List<PromotionAudit> entries) {
        if (entries == null || entries.isEmpty()) return Collections.emptyList();
        return entries.stream()
                .map(this::toAuditResponse)
                .toList();
    }

    // ═════════════════════════════════════════════════════════════════════════
    // PRIVATE HELPERS
    // ═════════════════════════════════════════════════════════════════════════

    /**
     * Builds the pre-formatted display string for a reward value.
     *
     * <p>UGX FLAT_OFF values use {@code %,d} for thousand separators and
     * no decimals — correct for whole-shilling amounts.
     * PERCENTAGE_OFF values are whole-number integers — no decimal point.
     *
     * @param reward the reward entity, must not be null
     * @return a human-readable string safe for display in the cart UI
     *         and order confirmation emails
     */
    private String formatRewardValue(PromotionReward reward) {
        return switch (reward.getRewardType()) {
            case PERCENTAGE_OFF ->
                    reward.getValue() + "% off your order";
            case FLAT_OFF ->
                    // %,d formats 5000 as "5,000" — no decimals, correct for UGX
                    String.format("UGX %,d off your order", reward.getValue());
            case FREE_SHIPPING ->
                    "Free shipping applied";
            case FREE_ITEM ->
                    "Free item added to your order";
        };
    }
}